<!DOCTYPE html>
<html lang="en" ng-app="silexCasts">
<head>
	<meta charset="UTF-8">
	<title>Silex com AngularJS</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
</head>
<body ng-controller="FirstCtrl">
	<h1>Silex com Angular - <?=$this->name;?></h1>
	<div class="row">
		<div class="container" >
		    <table class="table">
		    	<thead>
		    		<tr>
		    			<th>Nome</th>
	   			 		<th>Email</th>
		    		</tr>
		     	</thead>
		    	<tbody>
		    		<tr ng-repeat="u in users">
		    			<td>{{u.name}}</td>
		    			<td>{{u.email}}</td>
		    		</tr>
		    	</tbody>
		    </table>
		</div>
	</div>
</body>
<script src="assets/js/angular/angular.min.js"></script>
<script src="assets/js/app.js"></script>
<script src="assets/js/controller.js"></script>
</html> 